#+STARTUP: overview
#+STARTUP: hidestars
#+STARTUP: logdone
#+TAGS: { @OFFICE(o) @HOME(h) } @PHONE(p) @COMPUTER(c)
#+TAGS: 系统维护(a) 固定资产管理(e) 科技监管(r) 设备维护(m) 私事(b)
#+SEQ_TODO: TODO(t) STARTED(s) WAITING(w) APPT(a) | DONE(d) CANCELLED(c) DEFERRED(f)
#+COLUMNS: %25ITEM %10PRIORITY %f15TODO %40TAGS
 
* ubuntu服务器的安装

** IP地址的设置

   首先，激活服务器的网卡：
   sudo emacs /etc/network/interfaces

   并在interfaces中添加以下内容：

   auto etho iface etho inet static
   address 192.168.1.16 
   netmask 255.255.255.0 
   gateway 192.168.1.254

   然后修改resolv.conf配置DNS服务器的地址：

   sudo emacs /etc/resolv.conf

   在该文件中添加如下内容：

   nameserver 202.103.24.68

   完成后，重启networking服务：(如果使用ADSL上网，还需要设置pppoe等)

   sudo /etc/init.d/networking restart
        
** 安装OpenSSH服务器

   首先，安装openssh-server sudo apt-get install openssh-server。首先，
   您刚才实验远程登录的时候可能会发现，在输入完用户名后需要等很长一段时
   间才会提示输入密码。其实这是由于 sshd 需要反查客户端的 dns 信息导致
   的。我们可以通过禁用这个特性来大幅提高登录的速度。首先，打开
   sshd_config 文件：

   sudo nano /etc/ssh/sshd_config

   在sshd_config最后一行加上
   
   UseDNS no

   然后重新启动 ssh 服务即可：

   sudo /etc/init.d/ssh restart

** 利用 PuTTy 通过证书认证登录服务器

   SSH 服务中，所有的内容都是加密传输的，安全性基本有保证。但是如果能使用
   证书认证的话，安全性将会更上一层楼，而且经过一定的设置，还能实现证书认
   证自动登录的效果。

   首先修改 sshd_config 文件，开启证书认证选项：

   RSAAuthentication yes
   PubkeyAuthentication yes
   AuthorizedKeysFile %h/.ssh/authorized_keys

   修改完成后重新启动 ssh 服务。

   下一步我们需要为 SSH 用户建立私钥和公钥。首先要登录到需要建立密钥的账
   户下，这里注意退出 root 用户，需要的话用 su 命令切换到其它用户下。然后
   运行：

   ssh-keygen

   这里，我们将生成的 key 存放在默认目录下即可。建立的过程中会提示输入
   passphrase，这相当于给证书加个密码，也是提高安全性的措施，这样即使证书
   不小心被人拷走也不怕了。当然如果这个留空的话，后面即可实现 PuTTy 通过
   证书认证的自动登录。

   ssh-keygen 命令会生成两个密钥，首先我们需要将公钥改名留在服务器上：

   cd ~/.ssh
   mv id_rsa.pub authorized_keys

   然后将私钥 id_rsa 从服务器上复制出来，并删除掉服务器上的 id_rsa 文件。

   服务器上的设置就做完了，下面的步骤需要在客户端电脑上来做。首先，我们需
   要将 id_rsa 文件转化为 PuTTy 支持的格式。这里我们需要利用 PuTTyGEN 这个
   工具：

   点击 PuTTyGen 界面中的 Load 按钮，选择 id_rsa 文件，输入passphrase（如
   果有的话），然后再点击 Save PrivateKey 按钮，这样 PuTTy接受的私钥就做好
   了。

   打开 PuTTy，在 Session 中输入服务器的 IP 地址，在Connection->SSH->Auth
   下点击 Browse 按钮，选择刚才生成好的私钥。然后回到 Connection 选项，在
   Auto-login username 中输入证书所属的用户名。回到 Session 选项卡，输入个
   名字点 Save 保存下这个 Session。点击底部的Open 应该就可以通过证书认证登
   录到服务器了。如果有 passphrase 的话，登录过程中会要求输入 passphrase，
   否则将会直接登录到服务器上，非常的方便。


** 安装Putty Session Manager

   通过安装Putty Session Manager(PSM)后，PSM可以开机时自动启动，并且可
   以管理Putty的Session，可以设置快捷键来快速启动Putty Sessions。

* Emacs使用技巧

** Mark Ring使用
   
   在buffer之内Emacs会默认保留16个跳转Mark，在Mark之间进行跳转时使用
   C-u M-@来进行设置。通过设置`set-mark-command-repeat-pop'为non-nil,可
   以在第一次使用C-u M-@跳转后，接着使用M-@来进行跳转。

** Magit

   [[http://zagadka.vim.bytemark.co.uk/magit/magit.html][Magit User Manual]]

** Fold

   在使用fold-dwim来作fold的时候，需要打开hs-minor-mode，
   outline-minor-mode，或folding-mode。可以通过3个通用的命令来进行
   folding。分别为fold-dwim-toggle， fold-dwim-hide-all，
   fold-dwim-show-all。

** Gnus
*** 快捷键使用
    | Mode    | Key       | Comment                                 |
    |---------+-----------+-----------------------------------------|
    | Group   | AA        | 列出所有新闻组                          |
    |         | u         | 订阅新闻组                              |
    |         | L         | 显示订阅新闻组                          |
    |         | l         | 显示有未读邮件或新闻的组                |
    |         | u         | 退订新闻组，并未删除。L命令可以显示出来 |
    |         | C-k       | 彻底删除                                |
    |         | g         | 查看新邮件或消息                        |
    |         | c         | 当前新闻组标记为已读                    |
    |         | C         | 所有新闻组标记为已读                    |
    |         | m         | 创建新邮件                              |
    |         | a         | 发帖子                                  |
    | Summary | a         | 发帖子(post article)                    |
    |         | f         | 回帖子(follow up)                       |
    |         | F         | 回帖子，含引用                   |
    |         | d         | 标记为已读                              |
    |         | ！        | 保留标记(ticked)，一直可见              |
    |         | ?         | 休眠标记(dormant)，跟贴后可见           |
    |         | r         | 回邮件                                  |
    |         | R         | 回邮件，含引用                          |
    |         | c         | 标记当前所有文章已读                    |
    |         | M-g       | 刷新邮件组或新闻组                      |
    |         | M-u       | 清除标记                                |
    |         | SPC       | Article Buffer翻页                      |
    |         | Backspace | Article Buffer向上翻页                  |
    |         | / o       | 显示旧消                                |
    |         | / a       | 查询给定作者消息                        |
    |         | C-u / a   | 反向查询                                |
    |         | / /       | 根据主题查询                            |
    |         | / x       | 根据邮件头查询                          |
    |         | / t       | 根据时间查询                            |
    |         | / w       | remove previous query limit             |
    |         | C-u / w   | remove all query limit                  |
    |         | M-s       | 查询Article Buffer的内容                |
    |         | M-r       | 向前查询Article Buffer内容              |
    | Article | C-c C-c   | 发送                                    |
    |         | C-c C-d   | 保存为草稿                              |
    |         | C-c C-k   | 删除                                    |
    |         | C-c C-m f | 粘贴附件                                |
    |         | M-q       | 重排段落                                |
    |         |           |                                         |

    其他有关配置信息参见sachachua的文章[fn:1]

** Misc Tips

   当使用completion的时候，用M-v可以跳入completion list buffer，然后就
   可以在completion list buffer中选择对应的选项了。

* Ruby的安装与使用

** Ruby的安装

   在ubuntu中，通过apt-get来安装系统ruby1.9包(因为ruby1.9自身已经包含
   rubygems了，不需要额外安装rubygems)。

   apt-get install ruby1.9

   安装好后，通过rubygem来安装rvm

   gem install rvm

   这样，就可以通过rvm来进行多个ruby版本的安装了。但是在正式安装之前，
   需要根据rvm的提示说明来安装好curl, patch, build-essential等软件或系
   统。

   rvm install 1.9.2-head
   rvm use ruby-1.9.2-head --default

   通过上面的命令安装好ruby后，执行rvm use来设置系统默认使用的ruby版本。

** Rubygems的安装

   如项目依赖于其他的第三方ruby gems，可以通过bundler来进行ruby软件包
   之间的依赖管理。

   gem install bundler
   bundle install

   如在安装过程中报错，一般都是ruby软件包依赖的第三方package未安装。如
   安装nokogiri过程中，就需要先安装：

   sudo apt-get install libxml2 libxml2-dev libxslt1 libxslt1-dev。
   
   安装sqlite3,需要先安装：

   sudo apt-get install libsqlite3-0 libsqlit3-dev sqlite3


* Footnotes

[fn:1] http://sachachua.com/notebook/wickedcool/wc-emacs-06-gnus.html
